version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ts-project-nest-next-graphql-hasura
    ports:
      - 5433:5433 # このポートは適切に設定されていますか？
    volumes:
      - ./docker/postgres/init.d:/docker-entrypoint-initdb.d
      - ./docker/postgres/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    hostname: ts-project-nest-next-graphql-hasura
    restart: always
    user: root